name: Deploy Storybook to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_PAGES: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup package manger
        uses: pnpm/action-setup@v2
        with: 
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build-packages

      - name: Build Storybook
        run: pnpm --filter baka-storybook run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/storybook/storybook-static